name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches: main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: ${{ matrix.python-version }}-build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.9']
    steps:
      - uses: actions/checkout@v3.1.0
      - name: Setup Python
        uses: actions/setup-python@v4.4.0
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - run: | # install package and test requirements as well as package
          python -m pip install -r requirements.txt
          python -m pip install nbconvert
          python -m pip list
      - name: Running Jupyter Notebooks
        run: |
          for nb in notebooks/*.ipynb; do echo $nb; time jupyter nbconvert --to notebook --execute $nb --ExecutePreprocessor.kernel_name=python3 --inplace; done
